### PR TITLE
Adding some pictures to website

### PR DESCRIPTION
**Pull request by jmcq89**

### CODE REVIEW

**Comment by mmp2** [comment]
http://www.stat.washington.edu/mmp/megaman.html

here is a place from which you can extract text. i made this
independently of jake, but now i think it's superfluous and i will
delete it (as soon as you don't need it any longer for inspiration)



-- 
_______________________________________________________________________
      Marina Meila
  ,_ o  ACMS Director         University of Washington       Box  354322
 / //\   Professor of Statistics                  Seattle WA 98195-4322
__\>>_|__ mmp@stat.washington.edu               phone: 206-543-8484
   \\,     www.stat.washington.edu/mmp      office: Padelford B-321
_______________________________________________________________________

**Comment by jmcq89** [comment]
I saved the HTML file of this for reference so you can delete it if you
want.

I think the "best" way to do this might be to have a second image with the
caption included in the .png file. Then when you click the first image it
re-directs to the one with the caption.

Jake might have a better idea.

-James

**Comment by mmp2** [comment]
how about a html file including the image (larger) and the caption? when
you click on the small image, you get to this one. if we want to edit the
caption, html is much easier.

Marina

**Comment by jmcq89** [comment]
I agree that we should make the caption easy to edit. I couldn't make the re-direct work so I'll have to figure out the best way to do this I might just have to work in html instead of the Sphinx syntax. 

James

**Pull request merged**
