### PR TITLE
Visualization tools and riemannian relaxation optimize bug fix

### PR DESCRIPTION
**Pull request by yuchaz**
1. Implement visualization tools, 3D covariance plotter.
2. Fix riemannian relaxation learning rate not updated issue (python 2.7)
3. Add more docstrings in riemannian relaxation.

### CODE REVIEW

**Comment by jmcq89** [comment]
Great stuff YuChia let me know if you need me to merge this or if you have permissions :)

**Comment by mmp2** [comment]
Hi James, Yuchia,

I think Yuchia is added as a collaborator, right?

Cheers,

Marina

-- 
_______________________________________________________________________
      Marina Meila
  ,_ o  ACMS Director         University of Washington       Box  354322
 / //\   Professor of Statistics                  Seattle WA 98195-4322
__\>>_|__ mmp@stat.washington.edu               phone: 206-543-8484
   \\,     www.stat.washington.edu/mmp      office: Padelford B-321
_______________________________________________________________________

**Comment by mmp2** [comment]
Did you also fix the little bug in spectral_embeding? 

Marina

YuChia Chen writes:
 > 1. Implement visualization tools, 3D covariance plotter.
 > 2. Fix riemannian relaxation learning rate not updated issue (python 2.7)
 > 3. Add more docstrings in riemannian relaxation.
 > You can view, comment on, or merge this pull request online at:
 > 
 >   https://github.com/mmp2/megaman/pull/80
 > 
 > -- Commit Summary --
 > 
 >   * Riemannian relaxation implemented.
 >   * Code refactoring and add documentations
 >   * Merge branch 'development'
 >   * Fix python2 syntax bugs and Update .travis.yml
 >   * Fixed syntax bugs in python2.7 and 3.4
 >   * Merge branch 'master' of https://github.com/mmp2/megaman
 >   * matching coding styles and adding more comments
 >   * fix projected class sidx not defined bug
 >   * add visualization and notebook for riemannian relaxation tutorial
 >   * Merge branch 'visual-documentations'
 >   * bug fixs for python2.7 and 3.4 compatibility
 >   * debugging python2.7 not optimizing issue
 >   * Megaman visualization tools added. Hourglass data generation added
 > 
 > -- File Changes --
 > 
 >     M README.md (4)
 >     M megaman/datasets/__init__.py (3)
 >     M megaman/datasets/datasets.py (61)
 >     A megaman/plotter/__init__.py (4)
 >     A megaman/plotter/covar_plotter3.py (177)
 >     A megaman/plotter/plotter.py (49)
 >     A megaman/plotter/scatter_3d.py (66)
 >     A megaman/plotter/utils.py (92)
 >     M megaman/relaxation/__init__.py (4)
 >     M megaman/relaxation/optimizer.py (68)
 >     M megaman/relaxation/precomputed.py (66)
 >     R megaman/relaxation/riemannian_relaxation.py (101)
 >     M megaman/relaxation/tests/test_tracing_var.py (3)
 >     M megaman/relaxation/trace_variable.py (19)
 >     M megaman/relaxation/utils.py (3)
 >     M megaman/setup.py (1)
 >     M megaman/utils/analyze_dimension_and_radius.py (38)
 >     M megaman/utils/estimate_radius.py (87)
 > 
 > -- Patch Links --
 > 
 > https://github.com/mmp2/megaman/pull/80.patch
 > https://github.com/mmp2/megaman/pull/80.diff
 > 
 > -- 
 > You are receiving this because you are subscribed to this thread.
 > Reply to this email directly or view it on GitHub:
 > https://github.com/mmp2/megaman/pull/80

-- 
_______________________________________________________________________
      Marina Meila
  ,_ o  ACMS Director         University of Washington       Box  354322
 / //\   Professor of Statistics                  Seattle WA 98195-4322
__\>>_|__ mmp@stat.washington.edu               phone: 206-543-8484
   \\,     www.stat.washington.edu/mmp      office: Padelford B-321
_______________________________________________________________________

**Comment by yuchaz** [comment]
Hi Marina,

Oh I just forget to fix it, I will close this pull request and do it again when I fixed it.
I am in the contributor list, but not sure if it's the same as collaborator. And seems like I cannot merge the pull request.

**Pull request closed without merging**
